.TH "sunrise\-siren\-studio" 1 "28 May 2025" "v1.3.0" "Sunrise Siren Studio"
.SH "NAME"
Sunrise Siren Studio \- Control program for Sunrise Siren 3000

.SH "SYNOPSIS"
sunrise-siren-studio

.SH "REQUIREMENTS"
The most important requirement to use Sunrise Siren Studio, is a Sunrise Siren 3000: the most epic NeoPixel based alarm clock!

.SH "FEATURES"
\- Set custom colors
.TP
\- Set alarms individually for every day of the week
.TP
\- Set countdowns
.TP
\- Read light level, temperature and humidity
.TP
\- Custom mode, where every digit can have a unique color and every pixel can be enabled individually
.TP
\- And more!

.SH "AUTHOR"
Sunrise Siren Studio and the ESP32 firmware are proudly made by ngkon.

.SH "BUGS"
Bugs in both Sunrise Siren Studio and the ESP32 firmware can be reported on the dedicated GitHub page:
.PP
https://github.com/ngkon6/SunriseSiren3000/issues

.SH "COPYRIGHT"
© 2025 ngkon. All rights reserved. The Sunrise Siren 3000 project is licensed under the GNU General Public License v3.
